/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useState, useContext, useEffect } from 'react';

const translations = {
  vi: {
    // Header
    app: "Ứng dụng",
    heroTitle: "Khám phá thế giới cùng VigoTrip",
    heroTagline: "Đặt vé máy bay, tàu hỏa, xe khách & tour du lịch với giá tốt nhất",
    search: "Tìm kiếm",
    support: "CSKH",
    login: "Đăng nhập/Đăng ký",
    checkInQR: "Quét vé (Check-in)",

    // Auth Modal
    authTitle: "Đăng nhập / Đăng ký",
    emailPlaceholder: "Vui lòng nhập địa chỉ email",
    continueWithEmail: "Tiếp tục với email",
    or: "Hoặc",
    loginWithGoogle: "Đăng nhập bằng Google",
    loginWithFacebook: "Đăng nhập với Facebook",
    loginWithApple: "Đăng nhập với Apple",
    qrText: "Sử dụng ứng dụng để",
    qrHighlight: "đăng nhập bằng mã QR",

    // Password Step
    createAccount: "Tạo Tài Khoản",
    setPassword: "Đặt mật khẩu cho tài khoản mới của bạn:",
    password: "Mật khẩu",
    passwordRequirement: "Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ cái, chữ số và ký hiệu",
    registerAndLogin: "Đăng ký và Đăng nhập",
    notYou: "Không phải bạn?",
    termsPrefix: "Bằng việc đăng nhập hoặc đăng ký, bạn được xem như đã đồng ý với",
    termsAndConditions: "Điều Kiện Và Điều Khoản",
    privacyPolicy: "Tuyên Bố Quyền Riêng Tự",
    of: "của",

    // Language
    selectLanguage: "Chọn ngôn ngữ",
    language: "Ngôn ngữ",

    // Errors
    emailRequired: "Vui lòng nhập địa chỉ email",
    emailInvalid: "Email phải là Gmail (có đuôi @gmail.com)",
    passwordRequired: "Vui lòng nhập mật khẩu",
    passwordInvalid: "Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ cái, chữ số và ký hiệu",
    registerSuccess: "Đăng ký tài khoản {email} thành công!",

    // Booking Tabs & Sidebar
    flight: "Vé máy bay",
    train: "Vé tàu hỏa",
    bus: "Xe khách",
    package: "Đặt theo gói",
    bookingContent: "Nội dung đặt vé cho:",

    // Flight Search
    roundTrip: "Khứ hồi",
    oneWay: "Một chiều",
    multiCity: "Nhiều thành phố",
    directFlight: "Bay thẳng",
    from: "Từ",
    to: "Đến",
    selectDeparture: "Chọn điểm đi",
    selectDestination: "Chọn điểm đến",
    allVietnam: "Tất cả Việt Nam",
    northVietnam: "Miền Bắc",
    centralVietnam: "Miền Trung",
    southVietnam: "Miền Nam",
    departureDate: "Ngày đi",
    returnDate: "Ngày về",
    passengers: "Hành khách",
    adult: "Người lớn",
    child: "Trẻ em",
    infant: "Em bé",
    adultAge: "Người lớn (≥12 tuổi)",
    childAge: "Trẻ em (2-11 tuổi)",
    infantAge: "Em bé (<2 tuổi)",
    ageAdultHint: ">12 tuổi",
    ageChildHint: "2-11 tuổi",
    ageInfantHint: "<2 tuổi",
    class: "Hạng vé",
    economy: "Phổ thông",
    premium: "Phổ thông đặc biệt",
    business: "Thương gia",
    first: "Hạng nhất",
    apply: "Áp dụng",
    anywhere: "Mọi nơi",
    addFlight: "Thêm chuyến bay khác",

    // Train Search
    departureStation: "Ga khởi hành",
    arrivalStation: "Ga đến",
    departureTime: "Thời gian khởi hành",
    returnTime: "Giờ về",
    addReturn: "Thêm chuyến về",
    onlyHighSpeed: "Chỉ tàu cao tốc",
    exploreHotel: "Khám phá khách sạn",
    all: "Tất cả",
    vip: "VIP",

    // City Selector - Tabs
    vietnam: "Việt Nam",
    taiwan: "Đài Loan",
    japan: "Nhật Bản",
    uk: "Anh",
    searchCity: "Tìm kiếm thành phố hoặc mã sân bay...",

    // Vietnam Cities
    hanoi: "Hà Nội",
    hcmc: "TP. Hồ Chí Minh",
    danang: "Đà Nẵng",

    // Taiwan Cities
    taipei: "Đài Bắc",
    kaohsiung: "Cao Hùng",
    taichung: "Đài Trung",

    // Japan Cities
    tokyo: "Tokyo",
    osaka: "Osaka",
    nagoya: "Nagoya",
    sapporo: "Sapporo",
    fukuoka: "Fukuoka",

    // UK Cities
    london: "Luân Đôn",
    manchester: "Manchester",
    edinburgh: "Edinburgh",
    birmingham: "Birmingham",

    // Footer
    contactUs: "Liên Hệ Với Chúng Tôi",
    customerCare: "Chăm Sóc Khách Hàng",
    serviceGuarantee: "Bảo Đảm Dịch Vụ",
    moreServiceInfo: "Xem thêm thông tin dịch vụ",
    aboutTrip: "Về VigoTrip",
    news: "Tin Tức",
    careers: "Tuyển dụng",
    termsConditions: "Điều Khoản & Điều Kiện",
    aboutGroup: "Giới Thiệu Về Tập Đoàn VigoTrip",
    otherServices: "Các Dịch Vụ Khác",
    investorRelations: "Quan Hệ Đầu Tư",
    tripRewards: "Phần Thưởng VigoTrip",
    affiliateProgram: "Chương trình đối tác liên kết",
    listProperty: "Đăng Cơ Sở Lưu Trú",
    security: "Bảo Mật",
    paymentMethods: "Phương thức thanh toán",
    ourPartners: "Đối Tác Của Chúng Tôi",
    footerTagline: "Nền tảng đặt vé máy bay, tàu hỏa và xe khách trực tuyến hàng đầu. Cam kết giá tốt nhất, thao tác nhanh gọn và hỗ trợ 24/7.",
    securityBadge: "Bảo mật SSL 256-bit & PCI-DSS",
    transportPartnersTitle: "ĐỐI TÁC VẬN CHUYỂN",
    vietnamRailway: "Đường sắt Việt Nam (VNR)",
    busPartners: "Phương Trang (FUTA) • Hoàng Long",
    smartBookingPlatform: "Nền tảng đặt vé đa phương thức thông minh",
    hotlineLabel: "Hotline:",
    copyright: "Bản quyền © 2025 VigoTrip Travel VietNam Pte. Ltd. Bảo lưu mọi quyền. Nhà điều hành trang: VigoTrip Travel VietNam Pte. Ltd.",

    packageSubtitle: "Lựa chọn gói du lịch trọn gói với nhiều ưu đãi hấp dẫn",
    selectPackage: "Chọn gói",
    backToList: "Quay lại danh sách",
    detailedItinerary: "Lịch trình chi tiết",
    includes: "Bao gồm",
    priceFrom: "Giá từ",
    save: "Tiết kiệm",
    departurePoint: "Điểm khởi hành",
    destinationPoint: "Điểm đến",
    duration: "Thời gian",
    transportation: "Phương tiện",
    bookNow: "Đặt ngay",
    sharePackage: "Chia sẻ gói này",
    priceDisclaimer: "Giá có thể thay đổi theo ngày khởi hành và số lượng khách",
    reviews: "đánh giá",

    // PACKAGE SEARCH (Uses shared keys: roundTrip, oneWay, from, to, search, apply, departureDate, returnDate)
    hotel: "Khách sạn",
    hotelDestination: "Điểm đến",
    checkin: "Nhận phòng",
    checkout: "Trả phòng",
    nights: "đêm",
    rooms: " Số phòng",

    // Search Forms
    selectAirport: "Chọn sân bay",
    selectBusStation: "Chọn bến xe",
    selectTrainStation: "Chọn ga tàu",
    swapDestinations: "Đổi điểm đi/đến",
    searching: "Đang tìm...",
    searchFlight: "Tìm chuyến bay",
    searchBus: "Tìm chuyến xe",
    searchTrain: "Tìm chuyến tàu",
    viewCheapCalendar: "Xem lịch giá rẻ",
    loadingCalendar: "Đang tải...",
    calendar30Days: "Lịch giá 30 ngày tới",
    noCheapFlights: "Hiện chưa có chuyến đi phù hợp trong khoảng ngày này. Bạn có thể bỏ chọn \"tìm vé rẻ nhất\" và dùng tìm kiếm thường, hoặc đổi điểm đi/điểm đến/ngày khác.",

    // Booking Steps
    step1Title: "Chọn ghế",
    step2Title: "Hành khách",
    step3Title: "Dịch vụ",
    step4Title: "Thanh toán",
    step1: "Bước 1: Chọn hạng vé & ghế ngồi",
    step2: "Bước 2: Thông tin hành khách",
    step3: "Bước 3: Dịch vụ bổ sung",
    step4: "Bước 4: Xác nhận & Thanh toán",
    seatClassAll: "Tất cả",
    seatClassEco: "Phổ thông",
    seatClassBiz: "Thương gia",
    bookingSummary: "Thông tin đặt chỗ",
    totalCost: "Tổng chi phí",
    paymentDetails: "Chi tiết thanh toán",
    paymentVNPAY: "Thanh toán qua VNPay",
    bookTicketNow: "Đặt vé ngay",
    goBack: "Quay lại",
    nextStep: "Tiếp theo",
    reviewAndPay: "Xem lại & Thanh toán",
    successBooking: "Đặt vé thành công!",
    promoCodeLabel: "Mã khuyến mãi / phiếu quà tặng",
    applyPromo: "Xác nhận",
    promoInstruction: "Nhập mã nếu có để được giảm giá.",
    passengerLastName: "Họ *",
    passengerFirstName: "Tên & tên đệm *",
    dob: "Ngày sinh *",
    nationality: "Quốc tịch",
    phoneNumber: "Số điện thoại *",
    emailField: "Email *",
    memberCode: "Mã hội viên (nếu có)",
    receivePromo: "Nhận thông tin khuyến mãi",
    rememberInfo: "Lưu thông tin cho lần sau",
    selectSeatInstruction: "Chọn hạng sau đó bấm vào ghế muốn ngồi.",
    passengerInstruction: "Nhập thông tin cá nhân của hành khách. Các ô có dấu * là bắt buộc.",
    extrasInstruction: "Tùy chọn thêm các dịch vụ để chuyến đi thoải mái hơn.",
    reviewInstruction: "Kiểm tra lại mọi thông tin trước khi hoàn tất.",
    baggage: "Hành lý",
    meal: "Suất ăn",
    insurance: "Bảo hiểm",
    airportTransfer: "Xe đưa đón",
    free: "Miễn phí",
    processing: "Đang xử lý...",

    // Extra Strings
    adminTrips: "Admin Trips",
    adminReviews: "Quản lý đánh giá",
    providerReviews: "Đánh giá",
    revenue: "Doanh thu",
    refunds: "Hoàn tiền",
    account: "Tài khoản",
    bookingHistory: "Lịch sử đặt vé",
    logout: "Đăng xuất",

    // My Bookings
    yourBookings: "Lịch sử đặt vé",
    noBookings: "Bạn chưa có chuyến đi nào",
    noBookingsSub: "Hãy khám phá các chuyến bay, tàu hỏa và xe khách giá tốt nhất ngay hôm nay!",
    exploreTripsBtn: "Khám phá chuyến đi ngay",
    loadingBookings: "Đang tải dữ liệu lịch sử đặt vé...",
    sessionExpiredTitle: "Phiên đăng nhập đã hết hạn",
    sessionExpiredDesc: "Vui lòng đăng nhập tài khoản của bạn để tra cứu và quản lý toàn bộ vé đã đặt.",
    loginNowBtn: "Đăng nhập ngay",
    status: "Trạng thái",
    paid: "Đã thanh toán",
    confirmed: "Đã xác nhận",
    completed: "Đã hoàn thành",
    cancelled: "Đã hủy",
    pendingPayment: "Chờ thanh toán",
    statusPaid: "Đã thanh toán",
    statusConfirmed: "Đã xác nhận",
    statusCompleted: "Đã hoàn thành",
    statusCancelled: "Đã hủy/Hoàn",
    statusPending: "Chờ thanh toán",
    ticketCode: "Mã vé",
    bookedAt: "Đặt lúc",
    bookingCodePrefix: "Mã vé:",
    bookedAtPrefix: "Đặt lúc:",
    departurePrefix: "Khởi hành:",
    seatPrefix: "Ghế:",
    passengerPrefix: "Hành khách:",
    servicesPrefix: "Dịch vụ:",
    discountAppliedText: "(Đã áp dụng ưu đãi)",
    refundedAmountText: "Đã hoàn tiền:",
    pendingRefundBadge: "⏳ Đang chờ admin duyệt yêu cầu hoàn vé",
    rejectedRefundBadge: "❌ Yêu cầu hoàn tiền bị từ chối",
    qrTicketCodeBtn: "Mã vé QR",
    completeTripBtn: "Hoàn thành chuyến đi",
    payNowBtn: "Thanh toán ngay →",
    cancelRefundBtn: "Hủy / Hoàn vé",
    reviewedBadge: "✓ Đã đánh giá",
    sendReviewBtn: "Gửi Đánh Giá",
    confirmCompleteTripTitle: "Xác nhận hoàn thành chuyến đi",
    confirmCompleteTripMsg: "Bạn có chắc chắn chuyến đi này đã hoàn thành? Hệ thống sẽ gửi khảo sát dịch vụ qua Email của bạn.",
    tripCompletedToast: "Chuyến đi đã hoàn thành. Cảm ơn bạn!",
    ratingStarLabel: "Chọn số sao",
    ratingStarRequired: "Vui lòng chọn số sao đánh giá (1–5).",
    reviewModalTitle: "Đánh giá chuyến đi",
    reviewCommentLabel: "Nhận xét (tùy chọn)",
    reviewCommentPlaceholder: "Chia sẻ trải nghiệm của bạn về dịch vụ, ghế ngồi, đúng giờ...",
    reviewCancelBtn: "Hủy",
    reviewSubmitBtn: "Gửi Đánh Giá",
    reviewSubmittingBtn: "Đang gửi...",
    reviewSuccessTitle: "Cảm ơn bạn đã đánh giá!",
    reviewSuccessSub: "Phản hồi của bạn giúp chúng tôi cải thiện dịch vụ mỗi ngày.",
    reviewToast5Star: "🌟 Cảm ơn bạn đã đánh giá 5 sao tuyệt vời! Phản hồi của bạn là động lực rất lớn cho chúng tôi.",
    reviewToastOther: "Cảm ơn bạn đã gửi đánh giá! Phản hồi của bạn giúp chúng tôi nâng cao chất lượng dịch vụ.",
    ratingsScale1: "Tệ",
    ratingsScale2: "Không hài lòng",
    ratingsScale3: "Bình thường",
    ratingsScale4: "Tốt",
    ratingsScale5: "Tuyệt vời",
    refundModalTitle: "Xác nhận hoàn/hủy vé",
    refundTripLabel: "Chuyến:",
    refundDepLabel: "Khởi hành:",
    refundTotalPaidLabel: "Tổng tiền đã đặt:",
    refundPolicyTitle: "Chính sách áp dụng:",
    refundPenaltyFee: "Phí phạt",
    refundExpectedAmount: "Số tiền sẽ nhận lại:",
    refundReasonLabel: "Lý do hoàn vé",
    refundReasonPlaceholder: "Vui lòng cho biết lý do bạn muốn hoàn/hủy vé...",
    refundReasonRequired: "Vui lòng nhập lý do hoàn vé.",
    refundCloseBtn: "Đóng",
    refundSubmitBtn: "Gửi yêu cầu hoàn vé",
    refundSubmittingBtn: "Đang gửi yêu cầu...",
    refundSuccessTitle: "🎉 Yêu cầu hoàn vé đã được gửi thành công!",
    refundSuccessSub: "Vui lòng chờ Admin duyệt. Bạn có thể theo dõi trạng thái tại đây.",
    refundUnder4hText: "Dưới 4 tiếng đến lúc khởi hành. KHÔNG hỗ trợ hoàn vé.",
    refundUnder24hText: "Dưới 24 tiếng đến lúc khởi hành. PHÍ PHẠT LÀ 10%.",
    refundOver24hText: "Trước 24 tiếng khởi hành. HỖ TRỢ HOÀN TRẢ 100%.",
    qrModalTitle: "Mã vé của bạn",
    qrModalDesc: "Xuất trình mã này tại quầy để làm thủ tục check-in.",
    qrBookingId: "Mã đặt chỗ:",
    qrRoute: "Hành trình:",
    qrCloseBtn: "Đóng",

    // Chatbot Translations
    chatbotSupportBtn: "Hỗ trợ đặt vé",
    chatbotAssistantName: "Trợ lý VigoTrip",
    chatbotOnlineStatus: "Đang trực tuyến",
    chatbotConnectingStatus: "Đang kết nối...",
    chatbotMaintenanceStatus: "Bảo trì / Quá tải",
    chatbotMaintenanceNotice: "Hệ thống AI hiện đang bảo trì hoặc quá tải. Bạn vui lòng thử lại sau ít phút hoặc liên hệ hotline 1900 1234.",
    chatbotClearHistory: "Xóa",
    chatbotClearHistoryTitle: "Xóa lịch sử chat",
    chatbotNewChatMsg: "Cuộc hội thoại mới. Tôi có thể hỗ trợ gì cho bạn?",
    chatbotFaqTitle: "Câu hỏi phổ biến",
    chatbotHideFaq: "Ẩn",
    chatbotInputPlaceholder: "Nhập câu hỏi...",
    chatbotWelcomeMsg: "Xin chào. Tôi là trợ lý của **VigoTrip**. Tôi có thể hỗ trợ bạn tra cứu chuyến đi, tìm vé giá tốt hoặc giải đáp thắc mắc dịch vụ. Bạn cần hỗ trợ gì hôm nay?",
    chatbotFaqFlight: "Tìm vé máy bay rẻ nhất",
    chatbotFaqTrain: "Tìm vé tàu hỏa giá tốt",
    chatbotFaqBus: "Tìm vé xe khách hôm nay",
    chatbotFaqRefund: "Chính sách đổi trả và hủy vé",
    chatbotFaqPromo: "Mã giảm giá mới nhất",
    chatbotFaqBookings: "Xem vé đã đặt của tôi",
    chatbotFaqPayment: "Phương thức thanh toán",
    passengerList: "Danh sách hành khách",
    seat: "Ghế",
    passengerNameText: "Hành khách",
    ticketPrice: "Giá vé",
    cancelTicket: "Hủy vé",
    cancelTicketConfirmTitle: "Xác nhận hủy vé",
    cancelTicketConfirmDesc: "Bạn có chắc muốn hủy vé này? Giá vé sẽ được trừ khỏi tổng đơn hàng.",
    confirmComplete: "Bạn xác nhận chuyến đi này đã hoàn thành?",
    completeBookingBtn: "Hoàn thành",
    requestRefundBtn: "Yêu cầu hoàn tiền",
    submitReviewBtn: "Gửi Đánh Giá ⭐️",
    refundedAmount: "Được hoàn",
    noName: "Chưa có tên",

    // Refunds
    refundManagement: "Quản lý Yêu cầu Hoàn tiền",
    allFilter: "Tất cả",
    pendingFilter: "Chờ duyệt",
    approvedFilter: "Đã duyệt",
    rejectedFilter: "Từ chối",
    noRefunds: "Không có yêu cầu hoàn tiền nào.",
    refundRequest: "Yêu cầu hoàn tiền",
    refundReason: "Lý do yêu cầu",
    notePrefix: "Lưu ý",
    refundNote: "Yêu cầu hoàn tiền sẽ được nhà cung cấp xem xét và phản hồi. Bạn sẽ nhận được thông báo khi có kết quả.",
    cancelBtn: "Hủy",
    sendRefundRequest: "Gửi yêu cầu hoàn tiền",
    approveRefund: "✓ Duyệt",
    rejectRefund: "✕ Từ chối",
    providerNoteText: "Ghi chú",
    sentAt: "Gửi lúc",
    processedAt: "Xử lý lúc",
    rejectTitle: "Từ chối yêu cầu hoàn tiền",
    rejectReasonLabel: "Lý do từ chối (tùy chọn)",
    rejectConfirmBtn: "Xác nhận Từ chối",
    refundRequestReasonCol: "Lý do yêu cầu hoàn tiền",

    // Reviews
    rating: "Số sao",
    commentText: "Bình luận",
    searchPlaceholder: "Tìm kiếm theo hành trình, hãng, hoặc nội dung...",
    userCol: "Người dùng",
    providerCol: "Nhà cung cấp",
    journeyCol: "Hành trình",
    noReviews: "Không tìm thấy đánh giá.",
    selectRating: "Chọn số sao",
    reviewCommentOption: "Nhận xét (tùy chọn)",

    // Revenue
    revenueTitle: "Thống kê Doanh thu",
    totalRevenue: "Tổng Doanh thu",
    totalBookings: "Tổng số vé/booking",
    revenueByMonth: "Doanh thu theo Tháng",
    revenueByService: "Tỷ lệ Doanh thu theo Dịch vụ",
    revenueByDate: "Chi tiết Doanh thu theo Ngày",
    dateCol: "Ngày",
    revenueCol: "Doanh thu",
    aiInsights: "Nhận định & Dự báo AI",
    aiAnalyzing: "AI đang phân tích dữ liệu...",
    getAIInsights: "Phân tích AI",

    // Package
    favoriteTours: "Tour Yêu thích",

    // Home Page Extras
    quickBooking: "Đặt vé nhanh",
    popularDestinations: "Điểm đến phổ biến",
    bestPriceAllAirlines: "Giá tốt nhất mọi hãng",
    easyBookingSeat: "Đặt nhanh, chọn chỗ ngồi",
    hundredsBusOperators: "Hàng trăm nhà xe uy tín",
    comboMoreSavings: "Combo tiết kiệm hơn",
    startingFrom: "Từ {price}",
    safePayment: "Thanh toán an toàn",
    instantConfirmation: "Xác nhận tức thì",
    support247: "Hỗ trợ 24/7",
    easyRefund: "Hoàn tiền dễ dàng",

    // Maintenance & Toast Messages
    underMaintenance: "Đang bảo trì",
    roundTripMaintenanceMsg: "⚠️ Tính năng vé Khứ hồi hiện đang bảo trì & nâng cấp hệ thống. Vui lòng sử dụng vé Một chiều quý khách nhé!",
    nhaTrang: "Nha Trang",

    // Filter & Sort & Trip List
    listBusTitle: "Danh sách chuyến xe khách",
    listTrainTitle: "Danh sách chuyến tàu hỏa",
    listFlightTitle: "Danh sách chuyến bay",
    showingTrips: "Hiển thị {filtered}/{total} chuyến phù hợp",
    sortByLabel: "Sắp xếp theo:",
    sortPriceAsc: "Giá vé: Thấp đến Cao",
    sortPriceDesc: "Giá vé: Cao đến Thấp",
    sortTimeAsc: "Giờ đi: Sớm nhất đến Muộn nhất",
    sortTimeDesc: "Giờ đi: Muộn nhất đến Sớm nhất",
    sortDurationAsc: "Thời gian chạy: Ngắn nhất",
    availableSeatsOnly: "Chỉ chuyến còn ghế trống",
    departureTimeRange: "Khung giờ khởi hành:",
    timeRangeAll: "Tất cả",
    timeRangeEarlyMorning: "Sáng sớm (0 - 6h)",
    timeRangeMorning: "Sáng (6 - 12h)",
    timeRangeAfternoon: "Chiều (12 - 18h)",
    timeRangeEvening: "Tối (18 - 24h)",
    busProvider: "Nhà xe:",
    trainProvider: "Hãng tàu:",
    airlineProvider: "Hãng bay:",
    clearBusFilter: "Xóa lọc nhà xe",
    clearTrainFilter: "Xóa lọc hãng tàu",
    clearAirlineFilter: "Xóa lọc hãng bay",
    noMatchingBusTrips: "Không có chuyến xe khách nào phù hợp với bộ lọc hiện tại. Hãy thử mở rộng khung giờ hoặc bỏ chọn lọc.",
    noMatchingTrainTrips: "Không có chuyến tàu hỏa nào phù hợp với bộ lọc hiện tại. Hãy thử mở rộng khung giờ hoặc bỏ chọn lọc.",
    noMatchingFlightTrips: "Không có chuyến bay nào phù hợp với bộ lọc hiện tại. Hãy thử mở rộng khung giờ hoặc bỏ lọc hãng.",

    // Trip Card Options
    cheapest: "RẺ NHẤT",
    busBadge: "XE KHÁCH",
    trainBadge: "TÀU HỎA",
    airlineBadge: "MÁY BAY",
    sleeperBus: "Xe giường nằm",
    expressTrain: "Tàu hỏa SE",
    commercialFlight: "Máy bay",
    directRoute: "Chạy thẳng",
    directFlightRoute: "Bay thẳng",
    availableSeats: "Chỗ trống",
    almostSoldOut: "Sắp hết vé!",
    pricePerPerson: "Giá/người",
    selectTicket: "Chọn vé",
    selected: "✓ Đã chọn",
    durationHours: "g",
    durationMins: "ph",
  },

  en: {
    // Header
    app: "App",
    heroTitle: "Explore the world with VigoTrip",
    heroTagline: "Book flights, trains, buses & tours at the best prices",
    search: "Search",
    support: "Support",
    login: "Login/Register",
    checkInQR: "Scan Ticket (Check-in)",

    // Auth Modal
    authTitle: "Login / Register",
    emailPlaceholder: "Please enter your email",
    continueWithEmail: "Continue with email",
    or: "Or",
    loginWithGoogle: "Login with Google",
    loginWithFacebook: "Login with Facebook",
    loginWithApple: "Login with Apple",
    qrText: "Use app to",
    qrHighlight: "login with QR code",

    // Password Step
    createAccount: "Create Account",
    setPassword: "Set password for your new account:",
    password: "Password",
    passwordRequirement: "Password must be at least 8 characters, including letters, numbers and symbols",
    registerAndLogin: "Register & Login",
    notYou: "Not you?",
    termsPrefix: "By logging in or registering, you agree to the",
    termsAndConditions: "Terms & Conditions",
    privacyPolicy: "Privacy Policy",
    of: "of",

    // Language
    selectLanguage: "Select language",
    language: "Language",

    // Errors
    emailRequired: "Please enter your email",
    emailInvalid: "Email must be Gmail (with @gmail.com)",
    passwordRequired: "Please enter password",
    passwordInvalid: "Password must be at least 8 characters, including letters, numbers and symbols",
    registerSuccess: "Account {email} registered successfully!",

    // Booking Tabs & Sidebar
    flight: "Flight Tickets",
    train: "Train Tickets",
    bus: "Bus Tickets",
    package: "Package Booking",
    bookingContent: "Booking content for:",

    // Flight Search
    roundTrip: "Round trip",
    oneWay: "One way",
    multiCity: "Multi-city",
    directFlight: "Direct flights only",
    from: "From",
    to: "To",
    selectDeparture: "Select departure",
    selectDestination: "Select destination",
    allVietnam: "All Vietnam",
    northVietnam: "Northern Vietnam",
    centralVietnam: "Central Vietnam",
    southVietnam: "Southern Vietnam",
    departureDate: "Departure",
    returnDate: "Return",
    passengers: "Passengers",
    adult: "Adult",
    child: "Child",
    infant: "Infant",
    adultAge: "Adults (≥12 years)",
    childAge: "Children (2-11 years)",
    infantAge: "Infants (<2 years)",
    ageAdultHint: ">12 yrs",
    ageChildHint: "2-11 yrs",
    ageInfantHint: "<2 yrs",
    class: "Class",
    economy: "Economy",
    premium: "Premium economy",
    business: "Business",
    first: "First class",
    apply: "Apply",
    flightHotel: "Flight + Hotel",
    anywhere: "Anywhere",
    addFlight: "Add another flight",

    // Train Search
    departureStation: "Departure station",
    arrivalStation: "Arrival station",
    departureTime: "Departure time",
    returnTime: "Return time",
    addReturn: "Add return",
    onlyHighSpeed: "High speed only",
    exploreHotel: "Explore hotels",
    all: "All",
    vip: "VIP",

    // City Selector - Tabs
    vietnam: "Vietnam",
    taiwan: "Taiwan",
    japan: "Japan",
    uk: "United Kingdom",
    searchCity: "Search city or airport code...",

    // Vietnam Cities
    hanoi: "Hanoi",
    hcmc: "Ho Chi Minh City",
    danang: "Da Nang",

    // Taiwan Cities
    taipei: "Taipei",
    kaohsiung: "Kaohsiung",
    taichung: "Taichung",

    // Japan Cities
    tokyo: "Tokyo",
    osaka: "Osaka",
    nagoya: "Nagoya",
    sapporo: "Sapporo",
    fukuoka: "Fukuoka",

    // UK Cities
    london: "London",
    manchester: "Manchester",
    edinburgh: "Edinburgh",
    birmingham: "Birmingham",

    // Footer
    contactUs: "Contact Us",
    customerCare: "Customer Care",
    serviceGuarantee: "Service Guarantee",
    moreServiceInfo: "More service information",
    aboutUs: "About VigoTrip",
    news: "News",
    careers: "Careers",
    termsConditions: "Terms & Conditions",
    aboutGroup: "About VigoTrip Group",
    otherServices: "Other Services",
    investorRelations: "Investor Relations",
    rewards: "VigoTrip Rewards",
    affiliateProgram: "Affiliate Program",
    listProperty: "List Your Property",
    security: "Security",
    paymentMethods: "Payment Methods",
    ourPartners: "Our Partners",
    footerTagline: "Leading online booking platform for flights, trains, and buses. Best fares guaranteed with fast booking and 24/7 support.",
    securityBadge: "256-bit SSL & PCI-DSS Secure",
    transportPartnersTitle: "TRANSPORT PARTNERS",
    vietnamRailway: "Vietnam Railways (VNR)",
    busPartners: "Phuong Trang (FUTA) • Hoang Long",
    smartBookingPlatform: "Smart multimodal travel booking platform",
    hotlineLabel: "Hotline:",
    copyright: "Copyright © 2025 VigoTrip Travel VietNam Pte. Ltd. All rights reserved. Operator: VigoTrip Travel VietNam Pte. Ltd.",

    packageSubtitle: "Choose an all-inclusive travel package with attractive offers",
    selectPackage: "Select package",
    backToList: "Back to list",
    detailedItinerary: "Detailed itinerary",
    includes: "Includes",
    priceFrom: "Price from",
    save: "Save",
    departurePoint: "Departure point",
    destinationPoint: "Destination",
    duration: "Duration",
    transportation: "Transportation",
    bookNow: "Book now",
    sharePackage: "Share this package",
    priceDisclaimer: "Prices may vary depending on departure date and number of guests",
    reviews: "reviews",

    // Package Search (Uses shared keys: search, apply, package, roundTrip, oneWay, from, to, departureDate, returnDate)
    hotel: "Hotel",
    hotelDestination: "Destination",
    checkin: "Check-in",
    checkout: "Check-out",
    nights: "nights",
    rooms: "rooms",

    // Search Forms
    selectAirport: "Select airport",
    selectBusStation: "Select bus station",
    selectTrainStation: "Select train station",
    swapDestinations: "Swap destinations",
    searching: "Searching...",
    searchFlight: "Find flights",
    searchBus: "Find buses",
    searchTrain: "Find trains",
    viewCheapCalendar: "View cheap calendar",
    loadingCalendar: "Loading...",
    calendar30Days: "30-day price calendar",
    noCheapFlights: "There are currently no suitable trips within these dates. You can uncheck \"find cheapest\" and use normal search, or change your origin/destination/dates.",

    // Booking Steps
    step1Title: "Select Seat",
    step2Title: "Passenger",
    step3Title: "Extras",
    step4Title: "Payment",
    step1: "Step 1: Select class & seats",
    step2: "Step 2: Passenger information",
    step3: "Step 3: Additional services",
    step4: "Step 4: Review & Payment",
    seatClassAll: "All",
    seatClassEco: "Economy",
    seatClassBiz: "Business",
    bookingSummary: "Booking Summary",
    totalCost: "Total Cost",
    paymentDetails: "Payment Details",
    paymentVNPAY: "Pay via VNPay",
    bookTicketNow: "Book Ticket",
    goBack: "Go Back",
    nextStep: "Next",
    reviewAndPay: "Review & Pay",
    successBooking: "Booking Successful!",
    promoCodeLabel: "Promo Code / Gift Voucher",
    applyPromo: "Apply",
    promoInstruction: "Enter a code if you have one.",
    passengerLastName: "Last Name *",
    passengerFirstName: "First & Middle Name *",
    dob: "Date of Birth *",
    nationality: "Nationality",
    phoneNumber: "Phone Number *",
    emailField: "Email *",
    memberCode: "Member Code (Optional)",
    receivePromo: "Receive promotional offers",
    rememberInfo: "Remember info for next time",
    selectSeatInstruction: "Select class and click on your desired seat.",
    passengerInstruction: "Enter passenger details. Fields with * are required.",
    extrasInstruction: "Add optional services for a more comfortable trip.",
    reviewInstruction: "Please review all details before completing payment.",
    baggage: "Baggage",
    meal: "Meals",
    insurance: "Insurance",
    airportTransfer: "Transfer",
    free: "Free",
    processing: "Processing...",

    // Extra Strings
    adminTrips: "Admin Trips",
    adminReviews: "Admin Reviews",
    providerReviews: "Provider Reviews",
    revenue: "Revenue",
    refunds: "Refunds",
    account: "Account",
    bookingHistory: "Booking History",
    logout: "Logout",

    // My Bookings
    yourBookings: "Booking History",
    noBookings: "You have no bookings yet",
    noBookingsSub: "Discover flights, trains, and buses at the best prices today!",
    exploreTripsBtn: "Explore Trips Now",
    loadingBookings: "Loading booking history...",
    sessionExpiredTitle: "Session Expired",
    sessionExpiredDesc: "Please log in to view and manage all your booked tickets.",
    loginNowBtn: "Log In Now",
    status: "Status",
    paid: "Paid",
    confirmed: "Confirmed",
    completed: "Completed",
    cancelled: "Cancelled",
    pendingPayment: "Pending Payment",
    statusPaid: "Paid",
    statusConfirmed: "Confirmed",
    statusCompleted: "Completed",
    statusCancelled: "Cancelled/Refunded",
    statusPending: "Pending Payment",
    ticketCode: "Ticket Code",
    bookedAt: "Booked At",
    bookingCodePrefix: "Ticket Code:",
    bookedAtPrefix: "Booked at:",
    departurePrefix: "Departure:",
    seatPrefix: "Seat:",
    passengerPrefix: "Passenger:",
    servicesPrefix: "Services:",
    discountAppliedText: "(Discount applied)",
    refundedAmountText: "Refunded:",
    pendingRefundBadge: "⏳ Waiting for admin to approve refund request",
    rejectedRefundBadge: "❌ Refund request rejected",
    qrTicketCodeBtn: "QR Ticket",
    completeTripBtn: "Complete Trip",
    payNowBtn: "Pay Now →",
    cancelRefundBtn: "Cancel / Refund",
    reviewedBadge: "✓ Reviewed",
    sendReviewBtn: "Review Trip",
    confirmCompleteTripTitle: "Confirm Trip Completion",
    confirmCompleteTripMsg: "Are you sure this trip is completed? The system will send a service survey to your email.",
    tripCompletedToast: "Trip completed. Thank you!",
    ratingStarLabel: "Select rating",
    ratingStarRequired: "Please select a star rating (1–5).",
    reviewModalTitle: "Rate Your Trip",
    reviewCommentLabel: "Review (optional)",
    reviewCommentPlaceholder: "Share your experience about service, seating, punctuality...",
    reviewCancelBtn: "Cancel",
    reviewSubmitBtn: "Submit Review",
    reviewSubmittingBtn: "Submitting...",
    reviewSuccessTitle: "Thank you for your review!",
    reviewSuccessSub: "Your feedback helps us improve our service every day.",
    reviewToast5Star: "🌟 Thank you for the wonderful 5-star review! Your feedback means a lot to us.",
    reviewToastOther: "Thank you for submitting your review! It helps us improve our service.",
    ratingsScale1: "Terrible",
    ratingsScale2: "Poor",
    ratingsScale3: "Average",
    ratingsScale4: "Good",
    ratingsScale5: "Excellent",
    refundModalTitle: "Confirm Ticket Refund/Cancellation",
    refundTripLabel: "Trip:",
    refundDepLabel: "Departure:",
    refundTotalPaidLabel: "Total Paid:",
    refundPolicyTitle: "Applied Policy:",
    refundPenaltyFee: "Penalty Fee",
    refundExpectedAmount: "Refund Amount:",
    refundReasonLabel: "Refund Reason",
    refundReasonPlaceholder: "Please specify why you want to cancel/refund...",
    refundReasonRequired: "Please provide a reason for refund.",
    refundCloseBtn: "Close",
    refundSubmitBtn: "Submit Refund Request",
    refundSubmittingBtn: "Submitting...",
    refundSuccessTitle: "🎉 Refund request submitted successfully!",
    refundSuccessSub: "Please wait for Admin approval. You can track status here.",
    refundUnder4hText: "Less than 4 hours to departure. NO refund supported.",
    refundUnder24hText: "Under 24 hours to departure. 10% PENALTY FEE applies.",
    refundOver24hText: "Over 24 hours before departure. 100% FULL REFUND.",
    qrModalTitle: "Your Ticket QR Code",
    qrModalDesc: "Present this QR code at the counter for check-in.",
    qrBookingId: "Booking ID:",
    qrRoute: "Route:",
    qrCloseBtn: "Close",

    // Chatbot Translations
    chatbotSupportBtn: "Booking Assistant",
    chatbotAssistantName: "VigoTrip Assistant",
    chatbotOnlineStatus: "Online",
    chatbotConnectingStatus: "Connecting...",
    chatbotMaintenanceStatus: "Maintenance / Busy",
    chatbotMaintenanceNotice: "The AI service is currently under maintenance or busy. Please try again shortly or contact hotline 1900 1234.",
    chatbotClearHistory: "Clear",
    chatbotClearHistoryTitle: "Clear chat history",
    chatbotNewChatMsg: "New conversation. How can I assist you today?",
    chatbotFaqTitle: "Popular Questions",
    chatbotHideFaq: "Hide",
    chatbotInputPlaceholder: "Type a question...",
    chatbotWelcomeMsg: "Hello. I am the **VigoTrip** assistant. I can assist you with finding trips, getting the best ticket fares, or answering service questions. How can I help you today?",
    chatbotFaqFlight: "Find cheapest flight tickets",
    chatbotFaqTrain: "Find best train tickets",
    chatbotFaqBus: "Find bus tickets today",
    chatbotFaqRefund: "Refund & cancellation policy",
    chatbotFaqPromo: "Latest discount vouchers",
    chatbotFaqBookings: "View my booked tickets",
    chatbotFaqPayment: "Payment methods",
    passengerList: "Passenger List",
    seat: "Seat",
    passengerNameText: "Passenger",
    ticketPrice: "Ticket Price",
    cancelTicket: "Cancel Ticket",
    cancelTicketConfirmTitle: "Confirm Cancellation",
    cancelTicketConfirmDesc: "Are you sure you want to cancel this ticket? The ticket price will be deducted from the total order.",
    confirmComplete: "Do you confirm this trip is completed?",
    completeBookingBtn: "Complete",
    requestRefundBtn: "Request Refund",
    submitReviewBtn: "Submit Review ⭐️",
    refundedAmount: "Refunded",
    noName: "No Name",

    // Refunds
    refundManagement: "Refund Requests Management",
    allFilter: "All",
    pendingFilter: "Pending",
    approvedFilter: "Approved",
    rejectedFilter: "Rejected",
    noRefunds: "No refund requests found.",
    refundRequest: "Refund Request",
    refundReason: "Reason for request",
    notePrefix: "Note",
    refundNote: "Your refund request will be reviewed by the provider. You will be notified of the result.",
    cancelBtn: "Cancel",
    sendRefundRequest: "Send Refund Request",
    approveRefund: "✓ Approve",
    rejectRefund: "✕ Reject",
    providerNoteText: "Provider Note",
    sentAt: "Sent At",
    processedAt: "Processed At",
    rejectTitle: "Reject Refund Request",
    rejectReasonLabel: "Reject reason (optional)",
    rejectConfirmBtn: "Confirm Reject",
    refundRequestReasonCol: "Reason for refund request",

    // Reviews
    rating: "Rating",
    commentText: "Comment",
    searchPlaceholder: "Search by journey, provider, or content...",
    userCol: "User",
    providerCol: "Provider",
    journeyCol: "Journey",
    noReviews: "No reviews found.",
    selectRating: "Select rating",
    reviewCommentOption: "Comment (optional)",

    // Revenue
    revenueTitle: "Revenue Statistics",
    totalRevenue: "Total Revenue",
    totalBookings: "Total Bookings",
    revenueByMonth: "Revenue by Month",
    revenueByService: "Revenue by Service",
    revenueByDate: "Revenue Details by Date",
    dateCol: "Date",
    revenueCol: "Revenue",
    aiInsights: "AI Insights & Forecasting",
    aiAnalyzing: "AI is analyzing data...",
    getAIInsights: "AI Analysis",

    // Package
    favoriteTours: "Favorite Tours",

    // Home Page Extras
    quickBooking: "Quick Booking",
    popularDestinations: "Popular Destinations",
    bestPriceAllAirlines: "Best price from all airlines",
    easyBookingSeat: "Fast booking, choose seats",
    hundredsBusOperators: "Hundreds of trusted bus operators",
    comboMoreSavings: "Combo, save more",
    startingFrom: "From {price}",
    safePayment: "Secure Payment",
    instantConfirmation: "Instant Confirmation",
    support247: "24/7 Support",
    easyRefund: "Easy Refund",

    // Maintenance & Toast Messages
    underMaintenance: "Under Maintenance",
    roundTripMaintenanceMsg: "⚠️ Round-trip ticket feature is currently undergoing system maintenance & upgrade. Please use One-way tickets!",
    nhaTrang: "Nha Trang",

    // Filter & Sort & Trip List
    listBusTitle: "Bus Trip List",
    listTrainTitle: "Train Trip List",
    listFlightTitle: "Flight List",
    showingTrips: "Showing {filtered}/{total} matching trips",
    sortByLabel: "Sort by:",
    sortPriceAsc: "Price: Low to High",
    sortPriceDesc: "Price: High to Low",
    sortTimeAsc: "Departure: Earliest to Latest",
    sortTimeDesc: "Departure: Latest to Earliest",
    sortDurationAsc: "Duration: Shortest",
    availableSeatsOnly: "Available seats only",
    departureTimeRange: "Departure time slot:",
    timeRangeAll: "All",
    timeRangeEarlyMorning: "Early morning (0 - 6h)",
    timeRangeMorning: "Morning (6 - 12h)",
    timeRangeAfternoon: "Afternoon (12 - 18h)",
    timeRangeEvening: "Evening (18 - 24h)",
    busProvider: "Bus Operator:",
    trainProvider: "Train Line:",
    airlineProvider: "Airline:",
    clearBusFilter: "Clear bus operator filter",
    clearTrainFilter: "Clear train line filter",
    noMatchingBusTrips: "No bus trips match the current filter. Try expanding time range or clearing filters.",
    noMatchingTrainTrips: "No train trips match the current filter. Try expanding time range or clearing filters.",
    noMatchingFlightTrips: "No flights match the current filter. Try expanding time range or clearing airline filters.",

    // Trip Card Options
    cheapest: "CHEAPEST",
    busBadge: "BUS",
    trainBadge: "TRAIN",
    airlineBadge: "AIRLINE",
    sleeperBus: "Sleeper Bus",
    expressTrain: "Express Train",
    commercialFlight: "Airplane",
    directRoute: "Direct",
    directFlightRoute: "Direct flight",
    availableSeats: "Seats left",
    almostSoldOut: "Almost sold out!",
    pricePerPerson: "Price/person",
    selectTicket: "Select",
    selected: "✓ Selected",
    durationHours: "h",
    durationMins: "m",
  },




  ja: {
    // Header
    app: "アプリ",
    heroTitle: "VigoTripで世界を探索しよう",
    heroTagline: "航空券、列車、バス、ツアーを最安値で予約",
    search: "検索",
    support: "サポート",
    login: "ログイン/登録",
    checkInQR: "チケットスキャン",

    // Auth Modal
    authTitle: "ログイン / 登録",
    emailPlaceholder: "メールアドレスを入力してください",
    continueWithEmail: "メールで続ける",
    or: "または",
    loginWithGoogle: "Googleでログイン",
    loginWithFacebook: "Facebookでログイン",
    loginWithApple: "Appleでログイン",
    qrText: "アプリを使用して",
    qrHighlight: "QRコードでログイン",

    // Password Step
    createAccount: "アカウント作成",
    setPassword: "新しいアカウントのパスワードを設定:",
    password: "パスワード",
    passwordRequirement: "パスワードは8文字以上で、文字、数字、記号を含む必要があります",
    registerAndLogin: "登録してログイン",
    notYou: "違う方ですか？",
    termsPrefix: "ログインまたは登録により、",
    termsAndConditions: "利用規約",
    privacyPolicy: "プライバシーポリシー",
    of: "に同意したものとみなされます",

    // Language
    selectLanguage: "言語を選択",
    language: "言語",

    // Errors
    emailRequired: "メールアドレスを入力してください",
    emailInvalid: "メールはGmail（@gmail.com）である必要があります",
    passwordRequired: "パスワードを入力してください",
    passwordInvalid: "パスワードは8文字以上で、文字、数字、記号を含む必要があります",
    registerSuccess: "アカウント {email} が正常に登録されました",

    // Booking Tabs & Sidebar
    flight: "航空券",
    train: "鉄道チケット",
    bus: "バスチケット",
    package: "パッケージ予約",
    bookingContent: "予約内容:",

    // Flight Search
    roundTrip: "往復",
    oneWay: "片道",
    multiCity: "複数の都市",
    directFlight: "直行便のみ",
    from: "出発",
    to: "到着",
    selectDeparture: "出発地を選択",
    selectDestination: "到着地を選択",
    allVietnam: "ベトナム全土",
    northVietnam: "北部",
    centralVietnam: "中部",
    southVietnam: "南部",
    departureDate: "出発日",
    returnDate: "帰国日",
    passengers: "乗客",
    adult: "大人",
    child: "子供",
    infant: "幼児",
    adultAge: "大人 (12歳以上)",
    childAge: "子供 (2-11歳)",
    infantAge: "幼児 (2歳未満)",
    ageAdultHint: "12歳以上",
    ageChildHint: "2-11歳",
    ageInfantHint: "2歳未満",
    class: "クラス",
    economy: "エコノミー",
    premium: "プレミアムエコノミー",
    business: "ビジネス",
    first: "ファースト",
    apply: "適用",
    flightHotel: "飛行機 + ホテル",
    anywhere: "どこでも",
    addFlight: "別のフライトを追加",

    // Train Search
    departureStation: "出発駅",
    arrivalStation: "到着駅",
    departureTime: "出発時間",
    returnTime: "帰着時間",
    addReturn: "帰りを追加",
    onlyHighSpeed: "高速のみ",
    exploreHotel: "ホテルを探す",
    all: "すべて",
    vip: "VIP",

    // City Selector - Tabs
    vietnam: "ベトナム",
    taiwan: "台湾",
    japan: "日本",
    uk: "イギリス",
    searchCity: "都市名または空港コードを検索...",

    // Vietnam Cities
    hanoi: "ハノイ",
    hcmc: "ホーチミン",
    danang: "ダナン",

    // Taiwan Cities
    taipei: "台北",
    kaohsiung: "高雄",
    taichung: "台中",

    // Japan Cities
    tokyo: "東京",
    osaka: "大阪",
    nagoya: "名古屋",
    sapporo: "札幌",
    fukuoka: "福岡",

    // UK Cities
    london: "ロンドン",
    manchester: "マンチェスター",
    edinburgh: "エディンバラ",
    birmingham: "バーミンガム",

    // Footer
    contactUs: "お問い合わせ",
    customerCare: "カスタマーケア",
    serviceGuarantee: "サービス保証",
    moreServiceInfo: "サービス詳細",
    aboutUs: "VigoTripについて",
    news: "ニュース",
    careers: "採用情報",
    termsConditions: "利用規約",
    aboutGroup: "VigoTripグループについて",
    otherServices: "その他のサービス",
    investorRelations: "投資家情報",
    rewards: "VigoTrip特典",
    affiliateProgram: "アフィリエイトプログラム",
    listProperty: "宿泊施設を登録",
    security: "セキュリティ",
    paymentMethods: "お支払い方法",
    ourPartners: "パートナー",
    footerTagline: "航空券、列車、バスのオンライン予約をリードするプラットフォーム。最安値を保証し、迅速な手配と24時間サポートを提供します。",
    securityBadge: "256ビットSSL暗号化 & PCI-DSS準拠",
    transportPartnersTitle: "運行パートナー",
    vietnamRailway: "ベトナム国鉄 (VNR)",
    busPartners: "フンチャン (FUTA) • ホアンロン",
    smartBookingPlatform: "スマート複合交通チケット予約プラットフォーム",
    hotlineLabel: "ホットライン:",
    copyright: "著作権 © 2025 VigoTrip Travel VietNam Pte. Ltd. 全著作権所有。運営会社: VigoTrip Travel VietNam Pte. Ltd.",

    packageSubtitle: "魅力的なオファーがあるパッケージ旅行を選びましょう",
    selectPackage: "パッケージを選択",
    backToList: "リストに戻る",
    detailedItinerary: "詳細なスケジュール",
    includes: "含まれるもの",
    priceFrom: "最低価格",
    save: "割引",
    departurePoint: "出発地",
    destinationPoint: "目的地",
    duration: "所要時間",
    transportation: "交通手段",
    bookNow: "今すぐ予約",
    sharePackage: "このパッケージを共有",
    priceDisclaimer: "出発日や人数によって価格が変動する場合があります",
    reviews: "件のレビュー",

    // Package Search (Shared keys: search, apply, package, roundTrip, oneWay, from, to, departureDate, returnDate)
    hotel: "ホテル",
    hotelDestination: "目的地",
    checkin: "チェックイン",
    checkout: "チェックアウト",
    nights: "泊",
    rooms: "部屋",

    // Search Forms
    selectAirport: "空港を選択",
    selectBusStation: "バスターミナルを選択",
    selectTrainStation: "駅を選択",
    swapDestinations: "出発地/到着地を入れ替える",
    searching: "検索中...",
    searchFlight: "航空券を検索",
    searchBus: "バスを検索",
    searchTrain: "列車を検索",
    viewCheapCalendar: "格安カレンダー",
    loadingCalendar: "読み込み中...",
    calendar30Days: "30日間の価格カレンダー",
    noCheapFlights: "現在、これらの日付に適した旅行はありません。「最安値を検索」のチェックを外して通常の検索を使用するか、出発地/到着地/日付を変更できます。",

    // Booking Steps
    step1Title: "座席選択",
    step2Title: "乗客",
    step3Title: "追加サービス",
    step4Title: "支払い",
    step1: "ステップ1: クラスと座席の選択",
    step2: "ステップ2: 乗客情報",
    step3: "ステップ3: 追加サービス",
    step4: "ステップ4: 確認と支払い",
    seatClassAll: "すべて",
    seatClassEco: "エコノミー",
    seatClassBiz: "ビジネス",
    bookingSummary: "予約の概要",
    totalCost: "合計費用",
    paymentDetails: "支払いの詳細",
    paymentVNPAY: "VNPayで支払う",
    bookTicketNow: "今すぐ予約する",
    goBack: "戻る",
    nextStep: "次へ",
    reviewAndPay: "確認して支払う",
    successBooking: "予約が成功しました！",
    promoCodeLabel: "プロモコード / ギフト券",
    applyPromo: "適用",
    promoInstruction: "お持ちのコードを入力してください。",
    passengerLastName: "姓 *",
    passengerFirstName: "名 *",
    dob: "生年月日 *",
    nationality: "国籍",
    phoneNumber: "電話番号 *",
    emailField: "メールアドレス *",
    memberCode: "会員番号 (任意)",
    receivePromo: "プロモーション情報を受け取る",
    rememberInfo: "情報を保存する",
    selectSeatInstruction: "クラスを選択し、希望する座席をクリックしてください。",
    passengerInstruction: "乗客の情報を入力してください。*が付いている項目は必須です。",
    extrasInstruction: "オプションサービスを追加して、快適な旅行をお楽しみください。",
    reviewInstruction: "支払い手続きの前に、すべての詳細を確認してください。",
    baggage: "手荷物",
    meal: "お食事",
    insurance: "保険",
    airportTransfer: "送迎",
    free: "無料",
    processing: "処理中...",

    // Extra Strings
    adminTrips: "管理トリップ",
    adminReviews: "管理レビュー",
    providerReviews: "レビュー (プロバイダー)",
    revenue: "収益",
    refunds: "払い戻し",
    account: "アカウント",
    bookingHistory: "予約履歴",
    logout: "ログアウト",

    // My Bookings
    yourBookings: "予約履歴",
    noBookings: "予約がありません",
    noBookingsSub: "お得な航空券、列車、バスチケットを今すぐチェック！",
    exploreTripsBtn: "旅行を探す",
    loadingBookings: "予約履歴を読み込み中...",
    sessionExpiredTitle: "セッションの有効期限が切れました",
    sessionExpiredDesc: "予約したチケットを確認・管理するにはログインしてください。",
    loginNowBtn: "今すぐログイン",
    status: "ステータス",
    paid: "支払い済み",
    confirmed: "確認済み",
    completed: "完了",
    cancelled: "キャンセル",
    pendingPayment: "支払い待ち",
    statusPaid: "支払い済み",
    statusConfirmed: "確認済み",
    statusCompleted: "完了",
    statusCancelled: "キャンセル/返金済み",
    statusPending: "支払い待ち",
    ticketCode: "チケットコード",
    bookedAt: "予約日",
    bookingCodePrefix: "チケット番号:",
    bookedAtPrefix: "予約日時:",
    departurePrefix: "出発:",
    seatPrefix: "座席:",
    passengerPrefix: "乗客:",
    servicesPrefix: "サービス:",
    discountAppliedText: "(割引適用済み)",
    refundedAmountText: "返金済み:",
    pendingRefundBadge: "⏳ 管理者の返金承認待ち",
    rejectedRefundBadge: "❌ 返金リクエストが拒否されました",
    qrTicketCodeBtn: "QRチケット",
    completeTripBtn: "旅程完了",
    payNowBtn: "今すぐ支払う →",
    cancelRefundBtn: "キャンセル/払い戻し",
    reviewedBadge: "✓ 評価済み",
    sendReviewBtn: "レビューを投稿",
    confirmCompleteTripTitle: "旅程完了の確認",
    confirmCompleteTripMsg: "この旅程は完了しましたか？メールでアンケートをお送りします。",
    tripCompletedToast: "旅程が完了しました。ありがとうございます！",
    ratingStarLabel: "星数を選択",
    ratingStarRequired: "星数（1〜5）を選択してください。",
    reviewModalTitle: "旅程を評価",
    reviewCommentLabel: "コメント（任意）",
    reviewCommentPlaceholder: "サービス、座席、時間厳守などの体験を共有してください...",
    reviewCancelBtn: "キャンセル",
    reviewSubmitBtn: "レビューを送信",
    reviewSubmittingBtn: "送信中...",
    reviewSuccessTitle: "評価ありがとうございます！",
    reviewSuccessSub: "お客様のご意見はサービスの向上に役立ちます。",
    reviewToast5Star: "🌟 素晴らしい星5つの評価をありがとうございます！大変励みになります。",
    reviewToastOther: "レビューをいただきありがとうございます！サービス向上に役立てます。",
    ratingsScale1: "非常に悪い",
    ratingsScale2: "不満",
    ratingsScale3: "普通",
    ratingsScale4: "良い",
    ratingsScale5: "素晴らしい",
    refundModalTitle: "チケット払い戻し/キャンセルの確認",
    refundTripLabel: "便/路線:",
    refundDepLabel: "出発:",
    refundTotalPaidLabel: "予約合計金額:",
    refundPolicyTitle: "適用ポリシー:",
    refundPenaltyFee: "手数料",
    refundExpectedAmount: "返金予定額:",
    refundReasonLabel: "払い戻しの理由",
    refundReasonPlaceholder: "キャンセル/払い戻しの理由を入力してください...",
    refundReasonRequired: "払い戻しの理由を入力してください。",
    refundCloseBtn: "閉じる",
    refundSubmitBtn: "払い戻しリクエストを送信",
    refundSubmittingBtn: "送信中...",
    refundSuccessTitle: "🎉 払い戻しリクエストが正常に送信されました！",
    refundSuccessSub: "管理者の承認をお待ちください。ここでステータスを確認できます。",
    refundUnder4hText: "出発まで4時間未満です。払い戻しはできません。",
    refundUnder24hText: "出発まで24時間未満です。手数料10%がかかります。",
    refundOver24hText: "出発24時間以上前です。100%全額払い戻し可能です。",
    qrModalTitle: "あなたのチケットQRコード",
    qrModalDesc: "カウンターでこのQRコードを提示してチェックインしてください。",
    qrBookingId: "予約番号:",
    qrRoute: "旅程:",
    qrCloseBtn: "閉じる",

    // Chatbot Translations
    chatbotSupportBtn: "予約サポート",
    chatbotAssistantName: "VigoTrip アシスタント",
    chatbotOnlineStatus: "オンライン",
    chatbotConnectingStatus: "接続中...",
    chatbotMaintenanceStatus: "メンテナンス中 / 混雑中",
    chatbotMaintenanceNotice: "現在AIサービスはメンテナンス中または混雑しています。しばらくしてからもう一度お試しいただくか、ホットライン1900 1234までお問い合わせください。",
    chatbotClearHistory: "削除",
    chatbotClearHistoryTitle: "チャット履歴をクリア",
    chatbotNewChatMsg: "新しい会話です。何かお手伝いできることはありますか？",
    chatbotFaqTitle: "よくある質問",
    chatbotHideFaq: "非表示",
    chatbotInputPlaceholder: "質問を入力...",
    chatbotWelcomeMsg: "こんにちは。**VigoTrip** アシスタントです。旅行の検索、お得なチケット、サービスに関するお問い合わせなどをお手伝いします。本日はどのようなご用件でしょうか？",
    chatbotFaqFlight: "最安値の航空券を探す",
    chatbotFaqTrain: "お得な列車チケットを探す",
    chatbotFaqBus: "本日のバスチケットを探す",
    chatbotFaqRefund: "変更・キャンセル・返金規約",
    chatbotFaqPromo: "最新の割引クーポン",
    chatbotFaqBookings: "予約済みチケットを確認",
    chatbotFaqPayment: "お支払い方法",
    passengerList: "乗客リスト",
    seat: "座席",
    passengerNameText: "乗客",
    ticketPrice: "チケット価格",
    cancelTicket: "チケットをキャンセル",
    cancelTicketConfirmTitle: "キャンセルの確認",
    cancelTicketConfirmDesc: "このチケットをキャンセルしてもよろしいですか？チケット価格は合計金額から差し引かれます。",
    confirmComplete: "この旅行が完了したことを確認しますか？",
    completeBookingBtn: "完了",
    requestRefundBtn: "払い戻しをリクエスト",
    submitReviewBtn: "レビューを送信 ⭐️",
    refundedAmount: "払い戻し額",
    noName: "名前なし",

    // Refunds
    refundManagement: "払い戻しリクエスト管理",
    allFilter: "すべて",
    pendingFilter: "保留中",
    approvedFilter: "承認済み",
    rejectedFilter: "拒否済み",
    noRefunds: "払い戻しリクエストはありません。",
    refundRequest: "払い戻しリクエスト",
    refundReason: "リクエストの理由",
    notePrefix: "注意",
    refundNote: "払い戻しリクエストはプロバイダーによって審査されます。結果が通知されます。",
    cancelBtn: "キャンセル",
    sendRefundRequest: "払い戻しリクエストを送信",
    approveRefund: "✓ 承認",
    rejectRefund: "✕ 拒否",
    providerNoteText: "プロバイダーのメモ",
    sentAt: "送信日時",
    processedAt: "処理日時",
    rejectTitle: "払い戻しリクエストを拒否",
    rejectReasonLabel: "拒否の理由（オプション）",
    rejectConfirmBtn: "拒否を確認",
    refundRequestReasonCol: "払い戻しリクエストの理由",

    // Reviews
    rating: "評価",
    commentText: "コメント",
    searchPlaceholder: "旅行、プロバイダー、または内容で検索...",
    userCol: "ユーザー",
    providerCol: "プロバイダー",
    journeyCol: "旅行",
    noReviews: "レビューが見つかりません。",
    selectRating: "評価を選択する",
    reviewCommentOption: "コメント（オプション）",

    // Revenue
    revenueTitle: "収益統計",
    totalRevenue: "総収益",
    totalBookings: "総予約数",
    revenueByMonth: "月別収益",
    revenueByService: "サービス別収益",
    revenueByDate: "日別収益詳細",
    dateCol: "日付",
    revenueCol: "収益",

    // Package
    favoriteTours: "お気に入りツアー",

    // Home Page Extras
    quickBooking: "スピード予約",
    popularDestinations: "人気の目的地",
    bestPriceAllAirlines: "全航空会社の最安値",
    easyBookingSeat: "スピーディー予約・座席指定",
    hundredsBusOperators: "信頼できる数百のバス会社",
    comboMoreSavings: "お得なセットプラン",
    startingFrom: "{price} から",
    safePayment: "安全な決済",
    instantConfirmation: "即時確定",
    support247: "24時間年中無休サポート",
    easyRefund: "簡単な払い戻し",

    // Maintenance & Toast Messages
    underMaintenance: "メンテナンス中",
    roundTripMaintenanceMsg: "⚠️ 往復チケット機能は現在システムメンテナンス中です。片道チケットをご利用ください！",
    nhaTrang: "ニャチャン",

    // Filter & Sort & Trip List
    listBusTitle: "バス便一覧",
    listTrainTitle: "列車便一覧",
    listFlightTitle: "フライト一覧",
    showingTrips: "{total}件中 {filtered}件を表示",
    sortByLabel: "並び替え:",
    sortPriceAsc: "価格: 安い順",
    sortPriceDesc: "価格: 高い順",
    sortTimeAsc: "出発時間: 早い順",
    sortTimeDesc: "出発時間: 遅い順",
    sortDurationAsc: "所要時間: 短い順",
    availableSeatsOnly: "空席ありのみ",
    departureTimeRange: "出発時間帯:",
    timeRangeAll: "すべて",
    timeRangeEarlyMorning: "早朝 (0 - 6時)",
    timeRangeMorning: "朝 (6 - 12時)",
    timeRangeAfternoon: "昼・夕方 (12 - 18時)",
    timeRangeEvening: "夜 (18 - 24時)",
    busProvider: "バス会社:",
    trainProvider: "鉄道会社:",
    airlineProvider: "航空会社:",
    clearBusFilter: "バス会社フィルターを解除",
    clearTrainFilter: "鉄道会社フィルターを解除",
    noMatchingBusTrips: "条件に一致するバス便がありません。時間帯を広げるか、フィルターを解除してください。",
    noMatchingTrainTrips: "条件に一致する列車便がありません。時間帯を広げるか、フィルターを解除してください。",
    noMatchingFlightTrips: "条件に一致するフライトがありません。時間帯を広げるか、フィルターを解除してください。",

    // Trip Card Options
    cheapest: "最安値",
    busBadge: "バス",
    trainBadge: "列車",
    airlineBadge: "航空",
    sleeperBus: "寝台バス",
    expressTrain: "特急列車",
    commercialFlight: "航空機",
    directRoute: "直行",
    directFlightRoute: "直行便",
    availableSeats: "空席",
    almostSoldOut: "残りわずか！",
    pricePerPerson: "料金/人",
    selectTicket: "選択",
    selected: "✓ 選択中",
    durationHours: "時間",
    durationMins: "分",
  },



  zh: {
    // Header
    app: "應用程式",
    heroTitle: "與 VigoTrip 一起探索世界",
    heroTagline: "以最優惠的價格預訂機票、火車、巴士和旅遊",
    search: "搜尋",
    support: "客服",
    login: "登入 / 註冊",
    checkInQR: "掃描車票 (Check-in)",

    // Auth Modal
    authTitle: "登入 / 註冊",
    emailPlaceholder: "請輸入電子郵件",
    continueWithEmail: "繼續使用電子郵件",
    or: "或",
    loginWithGoogle: "使用Google登入",
    loginWithFacebook: "使用Facebook登入",
    loginWithApple: "使用Apple登入",
    qrText: "使用應用程式",
    qrHighlight: "使用QR碼登入",

    // Password Step
    createAccount: "創建帳戶",
    setPassword: "為您的新帳戶設置密碼：",
    password: "密碼",
    passwordRequirement: "密碼必須至少8個字符，包含字母、數字和符號",
    registerAndLogin: "註冊並登入",
    notYou: "不是您嗎？",
    termsPrefix: "通過登入或註冊，您被視為已同意",
    termsAndConditions: "條款與條件",
    privacyPolicy: "隱私權政策",
    of: "的",

    // Language
    selectLanguage: "選擇語言",
    language: "語言",

    // Errors
    emailRequired: "請輸入電子郵件",
    emailInvalid: "電子郵件必須是Gmail（帶@gmail.com）",
    passwordRequired: "請輸入密碼",
    passwordInvalid: "密碼必須至少8個字符，包含字母、數字和符號",
    registerSuccess: "帳戶 {email} 註冊成功！",

    // Booking Tabs & Sidebar
    flight: "機票",
    train: "火車票",
    bus: "巴士票",
    package: "套裝預訂",
    bookingContent: "預訂內容:",

    // Flight Search
    roundTrip: "往返",
    oneWay: "單程",
    multiCity: "多個城市",
    directFlight: "僅限直飛",
    from: "出發地",
    to: "目的地",
    selectDeparture: "選擇出發地",
    selectDestination: "選擇目的地",
    allVietnam: "越南全部",
    northVietnam: "北部",
    centralVietnam: "中部",
    southVietnam: "南部",
    departureDate: "出發日期",
    returnDate: "回程日期",
    passengers: "乘客",
    adult: "成人",
    child: "兒童",
    infant: "嬰兒",
    adultAge: "成人 (12歲以上)",
    childAge: "兒童 (2-11歲)",
    infantAge: "嬰兒 (2歲以下)",
    ageAdultHint: "12歲以上",
    ageChildHint: "2-11歲",
    ageInfantHint: "2歲以下",
    class: "艙等",
    economy: "經濟艙",
    premium: "豪華經濟艙",
    business: "商務艙",
    first: "頭等艙",
    apply: "套用",
    flightHotel: "機票 + 酒店",
    anywhere: "任何地方",
    addFlight: "添加其他航班",

    // Train Search
    departureStation: "出發站",
    arrivalStation: "到達站",
    departureTime: "出發時間",
    returnTime: "回程時間",
    addReturn: "添加回程",
    onlyHighSpeed: "僅高速",
    exploreHotel: "探索酒店",
    all: "全部",
    vip: "VIP",

    // City Selector - Tabs
    vietnam: "越南",
    taiwan: "台灣",
    japan: "日本",
    uk: "英國",
    searchCity: "搜尋城市或機場代碼...",

    // Vietnam Cities
    hanoi: "河內",
    hcmc: "胡志明市",
    danang: "峴港",

    // Taiwan Cities
    taipei: "台北",
    kaohsiung: "高雄",
    taichung: "台中",

    // Japan Cities
    tokyo: "東京",
    osaka: "大阪",
    nagoya: "名古屋",
    sapporo: "札幌",
    fukuoka: "福岡",

    // UK Cities
    london: "倫敦",
    manchester: "曼徹斯特",
    edinburgh: "愛丁堡",
    birmingham: "伯明翰",

    // Footer
    contactUs: "聯繫我們",
    customerCare: "客戶服務",
    serviceGuarantee: "服務保證",
    moreServiceInfo: "更多服務信息",
    aboutUs: "關於VigoTrip",
    news: "新聞",
    careers: "招聘",
    termsConditions: "條款與條件",
    aboutGroup: "關於VigoTrip集團",
    otherServices: "其他服務",
    investorRelations: "投資者關係",
    rewards: "VigoTrip獎勵",
    affiliateProgram: "聯盟計畫",
    listProperty: "註冊住宿",
    security: "安全",
    paymentMethods: "付款方式",
    ourPartners: "合作夥伴",
    footerTagline: "領先的航班、火車與客運線上預訂平台。保障最優惠價格、極速預訂及全天候24小時客服支援。",
    securityBadge: "256位元SSL加密與PCI-DSS安全認證",
    transportPartnersTitle: "交通合作夥伴",
    vietnamRailway: "越南鐵路 (VNR)",
    busPartners: "芳莊客運 (FUTA) • 黃龍客運",
    smartBookingPlatform: "智慧多運具行程預訂平台",
    hotlineLabel: "服務專線:",
    copyright: "版權所有 © 2025 VigoTrip Travel VietNam Pte. Ltd. 保留所有權利。運營商：VigoTrip Travel VietNam Pte. Ltd.",

    packageSubtitle: "选择具有丰富优惠的全包旅游套餐",
    selectPackage: "选择套餐",
    backToList: "返回列表",
    detailedItinerary: "详细行程",
    includes: "包含",
    priceFrom: "起价",
    save: "节省",
    departurePoint: "出发地",
    destinationPoint: "目的地",
    duration: "时长",
    transportation: "交通工具",
    bookNow: "立即预订",
    sharePackage: "分享此套餐",
    priceDisclaimer: "价格可能会根据出发日期和客人数量而变化",
    reviews: "条评论",


    //Package Search (Shared keys: search, apply, package, roundTrip, oneWay, from, to, departureDate, returnDate)
    hotel: "酒店",
    hotelDestination: "目的地",
    checkin: "入住",
    checkout: "退房",
    nights: "晚",
    rooms: "房間",

    // Search Forms
    selectAirport: "选择机场",
    selectBusStation: "选择巴士站",
    selectTrainStation: "选择火车站",
    swapDestinations: "交换出发地/目的地",
    searching: "搜寻中...",
    searchFlight: "查找航班",
    searchBus: "查找巴士",
    searchTrain: "查找火车",
    viewCheapCalendar: "查看特价日历",
    loadingCalendar: "载入中...",
    calendar30Days: "30天价格日历",
    noCheapFlights: "目前在这些日期内没有合适的行程。您可以取消选中“查找最便宜”，然后使用普通搜索，或者更改您的出发地/目的地/日期。",

    // Booking Steps
    step1Title: "选择座位",
    step2Title: "乘客",
    step3Title: "附加服务",
    step4Title: "支付",
    step1: "第一步：选择舱位与座位",
    step2: "第二步：乘客信息",
    step3: "第三步：附加服务",
    step4: "第四步：确认并付款",
    seatClassAll: "全部",
    seatClassEco: "经济舱",
    seatClassBiz: "商务舱",
    bookingSummary: "预订详情",
    totalCost: "总费用",
    paymentDetails: "付款明细",
    paymentVNPAY: "通过VNPay付款",
    bookTicketNow: "立即预订机票",
    goBack: "返回",
    nextStep: "下一步",
    reviewAndPay: "确认并付款",
    successBooking: "预订成功！",
    promoCodeLabel: "优惠码 / 礼品券",
    applyPromo: "确认",
    promoInstruction: "如果您有优惠码，请在此输入。",
    passengerLastName: "姓 *",
    passengerFirstName: "名 *",
    dob: "出生日期 *",
    nationality: "国籍",
    phoneNumber: "电话号码 *",
    emailField: "电子邮件 *",
    memberCode: "会员号 (选填)",
    receivePromo: "接收促销信息",
    rememberInfo: "保存信息供下次使用",
    selectSeatInstruction: "选择舱位后点击所需座位。",
    passengerInstruction: "输入乘客个人信息。带有 * 的为必填项。",
    extrasInstruction: "选择附加服务，让旅行更舒适。",
    reviewInstruction: "完成前请再次检查所有信息。",
    baggage: "行李",
    meal: "餐点",
    insurance: "保险",
    airportTransfer: "接机服务",
    free: "免费",
    processing: "正在处理...",

    // Extra Strings
    adminTrips: "管理行程",
    adminReviews: "管理評論",
    providerReviews: "評論 (提供商)",
    revenue: "收入",
    refunds: "退款",
    account: "帳戶",
    bookingHistory: "預訂歷史",
    logout: "登出",

    // My Bookings
    yourBookings: "預訂歷史",
    noBookings: "您尚無任何行程",
    noBookingsSub: "立即探索最優惠的機票、火車和客運班次！",
    exploreTripsBtn: "立即探索行程",
    loadingBookings: "正在加載預訂歷史...",
    sessionExpiredTitle: "登入已過期",
    sessionExpiredDesc: "請登入您的帳戶以查看和管理所有預訂車票。",
    loginNowBtn: "立即登入",
    status: "狀態",
    paid: "已付款",
    confirmed: "已確認",
    completed: "已完成",
    cancelled: "已取消",
    pendingPayment: "待付款",
    statusPaid: "已付款",
    statusConfirmed: "已確認",
    statusCompleted: "已完成",
    statusCancelled: "已取消/已退款",
    statusPending: "待付款",
    ticketCode: "票券代碼",
    bookedAt: "預訂於",
    bookingCodePrefix: "票號:",
    bookedAtPrefix: "預訂時間:",
    departurePrefix: "出發:",
    seatPrefix: "座位:",
    passengerPrefix: "乘客:",
    servicesPrefix: "服務:",
    discountAppliedText: "(已套用優惠)",
    refundedAmountText: "已退款:",
    pendingRefundBadge: "⏳ 等待管理員審核退款申請",
    rejectedRefundBadge: "❌ 退款申請已被拒絕",
    qrTicketCodeBtn: "QR車票",
    completeTripBtn: "完成行程",
    payNowBtn: "立即付款 →",
    cancelRefundBtn: "取消/退票",
    reviewedBadge: "✓ 已評價",
    sendReviewBtn: "發表評價",
    confirmCompleteTripTitle: "確認完成行程",
    confirmCompleteTripMsg: "您確定此行程已完成嗎？系統將向您的電子郵件發送服務問卷。",
    tripCompletedToast: "行程已完成。謝謝您！",
    ratingStarLabel: "選擇星級",
    ratingStarRequired: "請選擇評分星級 (1–5)。",
    reviewModalTitle: "評價您的行程",
    reviewCommentLabel: "評價（可選）",
    reviewCommentPlaceholder: "分享您對服務、座位、準時等方面的體驗...",
    reviewCancelBtn: "取消",
    reviewSubmitBtn: "提交評價",
    reviewSubmittingBtn: "提交中...",
    reviewSuccessTitle: "感謝您的評價！",
    reviewSuccessSub: "您的反饋有助於我們改進服務品質。",
    reviewToast5Star: "🌟 感謝您給予極佳的5星評價！您的支持是我們最大的動力。",
    reviewToastOther: "感謝您提交評價！這將幫助我們不斷提高服務水準。",
    ratingsScale1: "極差",
    ratingsScale2: "不滿意",
    ratingsScale3: "普通",
    ratingsScale4: "良好",
    ratingsScale5: "極佳",
    refundModalTitle: "確認退票/取消車票",
    refundTripLabel: "班次:",
    refundDepLabel: "出發:",
    refundTotalPaidLabel: "已付總金額:",
    refundPolicyTitle: "適用政策:",
    refundPenaltyFee: "手續費",
    refundExpectedAmount: "預計退款金額:",
    refundReasonLabel: "退款原因",
    refundReasonPlaceholder: "請說明您想退款/取消的原因...",
    refundReasonRequired: "請輸入退票/退款原因。",
    refundCloseBtn: "關閉",
    refundSubmitBtn: "提交退款申請",
    refundSubmittingBtn: "提交中...",
    refundSuccessTitle: "🎉 退款申請已成功提交！",
    refundSuccessSub: "請等待管理員審核。您可以在此追蹤狀態。",
    refundUnder4hText: "離出發不足4小時。不支援退票。",
    refundUnder24hText: "離出發不足24小時。手續費為10%。",
    refundOver24hText: "出發前24小時以上。支援100%全額退款。",
    qrModalTitle: "您的車票QR碼",
    qrModalDesc: "請在櫃檯出示此QR碼以辦理手續。",
    qrBookingId: "訂位代號:",
    qrRoute: "行程:",
    qrCloseBtn: "關閉",

    // Chatbot Translations
    chatbotSupportBtn: "預訂支援",
    chatbotAssistantName: "VigoTrip 智能助手",
    chatbotOnlineStatus: "在線",
    chatbotConnectingStatus: "連接中...",
    chatbotMaintenanceStatus: "維護中 / 繁忙",
    chatbotMaintenanceNotice: "AI服務目前正在維護或繁忙中。請稍後再試或致電熱線 1900 1234。",
    chatbotClearHistory: "清除",
    chatbotClearHistoryTitle: "清除對話記錄",
    chatbotNewChatMsg: "新對話。今天有什麼我可以為您服務的？",
    chatbotFaqTitle: "常見問題",
    chatbotHideFaq: "隱藏",
    chatbotInputPlaceholder: "輸入問題...",
    chatbotWelcomeMsg: "您好。我是 **VigoTrip** 智能助手。我可以為您查詢班次、尋找優惠票價或解答服務疑問。今天需要什麼協助呢？",
    chatbotFaqFlight: "尋找最便宜機票",
    chatbotFaqTrain: "尋找特惠火車票",
    chatbotFaqBus: "尋找今日客運票",
    chatbotFaqRefund: "退改簽政策",
    chatbotFaqPromo: "最新優惠券代碼",
    chatbotFaqBookings: "查看我的預訂車票",
    chatbotFaqPayment: "付款方式",
    passengerList: "乘客名單",
    seat: "座位",
    passengerNameText: "乘客",
    ticketPrice: "票價",
    cancelTicket: "取消票券",
    cancelTicketConfirmTitle: "確認取消",
    cancelTicketConfirmDesc: "您確定要取消此票券嗎？票價將從總訂單中扣除。",
    confirmComplete: "您確認此行程已完成嗎？",
    completeBookingBtn: "完成",
    requestRefundBtn: "請求退款",
    submitReviewBtn: "提交評論 ⭐️",
    refundedAmount: "已退款",
    noName: "無名",

    // Refunds
    refundManagement: "退款請求管理",
    allFilter: "全部",
    pendingFilter: "待處理",
    approvedFilter: "已批准",
    rejectedFilter: "已拒絕",
    noRefunds: "未找到退款請求。",
    refundRequest: "退款請求",
    refundReason: "請求原因",
    notePrefix: "注意",
    refundNote: "您的退款請求將由提供商審查。您將收到結果通知。",
    cancelBtn: "取消",
    sendRefundRequest: "發送退款請求",
    approveRefund: "✓ 批准",
    rejectRefund: "✕ 拒絕",
    providerNoteText: "提供商備註",
    sentAt: "發送時間",
    processedAt: "處理時間",
    rejectTitle: "拒絕退款請求",
    rejectReasonLabel: "拒絕原因 (可選)",
    rejectConfirmBtn: "確認拒絕",
    refundRequestReasonCol: "退款請求原因",

    // Reviews
    rating: "評分",
    commentText: "評論",
    searchPlaceholder: "按旅程、提供商或內容搜索...",
    userCol: "用戶",
    providerCol: "提供商",
    journeyCol: "旅程",
    noReviews: "未找到評論。",
    selectRating: "選擇評分",
    reviewCommentOption: "評論 (可選)",

    // Revenue
    revenueTitle: "收入統計",
    totalRevenue: "總收入",
    totalBookings: "總預訂數",
    revenueByMonth: "按月收入",
    revenueByService: "按服務收入",
    revenueByDate: "按日期收入明細",
    dateCol: "日期",
    revenueCol: "收入",

    // Package
    favoriteTours: "收藏的行程",

    // Home Page Extras
    quickBooking: "快速預訂",
    popularDestinations: "熱門目的地",
    bestPriceAllAirlines: "各大航空公司最優價",
    easyBookingSeat: "快速預訂，自由選座",
    hundredsBusOperators: "數百家優質客運公司",
    comboMoreSavings: "超值組合更省錢",
    startingFrom: "起價 {price}",
    safePayment: "安全支付",
    instantConfirmation: "即時確認",
    support247: "24/7 客服支持",
    easyRefund: "輕鬆退款",

    // Maintenance & Toast Messages
    underMaintenance: "維護中",
    roundTripMaintenanceMsg: "⚠️ 往返機票功能目前正在進行系統維護與升級。請使用單程機票！",
    nhaTrang: "芽莊",

    // Filter & Sort & Trip List
    listBusTitle: "客運班次列表",
    listTrainTitle: "火車班次列表",
    listFlightTitle: "航班列表",
    showingTrips: "顯示 {filtered}/{total} 個符合班次",
    sortByLabel: "排序方式:",
    sortPriceAsc: "票價: 從低到高",
    sortPriceDesc: "票價: 從高到低",
    sortTimeAsc: "出發時間: 從早到晚",
    sortTimeDesc: "出發時間: 從晚到早",
    sortDurationAsc: "運行時間: 最短",
    availableSeatsOnly: "僅顯示有空位班次",
    departureTimeRange: "出發時段:",
    timeRangeAll: "全部",
    timeRangeEarlyMorning: "清晨 (0 - 6時)",
    timeRangeMorning: "上午 (6 - 12時)",
    timeRangeAfternoon: "下午 (12 - 18時)",
    timeRangeEvening: "晚上 (18 - 24時)",
    busProvider: "客運公司:",
    trainProvider: "鐵路公司:",
    airlineProvider: "航空公司:",
    clearBusFilter: "清除客運篩選",
    clearTrainFilter: "清除鐵路篩選",
    noMatchingBusTrips: "沒有符合當前篩選條件的客運班次。請嘗試擴大時段或清除篩選。",
    noMatchingTrainTrips: "沒有符合當前篩選條件的火車班次。請嘗試擴大時段或清除篩選。",
    noMatchingFlightTrips: "沒有符合當前篩選條件的航班。請嘗試擴大時段或清除篩選。",

    // Trip Card Options
    cheapest: "最優惠",
    busBadge: "客運",
    trainBadge: "火車",
    airlineBadge: "航空",
    sleeperBus: "臥舖客運",
    expressTrain: "特快火車",
    commercialFlight: "客機",
    directRoute: "直達",
    directFlightRoute: "直飛",
    availableSeats: "空位",
    almostSoldOut: "即將售罄！",
    pricePerPerson: "價格/人",
    selectTicket: "選擇",
    selected: "✓ 已選擇",
    durationHours: "小時",
    durationMins: "分",
  }
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState(() => {
    try {
      const savedLanguage = localStorage.getItem("language");
      if (savedLanguage) {
        return JSON.parse(savedLanguage);
      }
    } catch {
      // Ignore parse error
    }
    return { code: 'vi', name: 'Tiếng Việt', flag: null };
  });

  const t = React.useMemo(() => {
    return translations[currentLanguage.code] || translations.vi;
  }, [currentLanguage.code]);

  useEffect(() => {
    document.documentElement.lang = currentLanguage.code;
  }, [currentLanguage.code]);

  const changeLanguage = React.useCallback((language) => {
    setCurrentLanguage(language);
    localStorage.setItem("language", JSON.stringify(language));
    document.documentElement.lang = language.code;
    globalThis.dispatchEvent(new CustomEvent('languageChange', { detail: { language: language.code } }));
  }, []);

  const value = React.useMemo(
    () => ({ currentLanguage, t, changeLanguage, translations }),
    [currentLanguage, t, changeLanguage]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};